//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_management_system_backend.MVC.Models
{
    using System;

    public partial class BillProduct
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> billId { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
