//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_management_system_backend.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
        public string status { get; set; }
    }
}
