//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe_management_system_backend.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string name { get; set; }
        public string contactNumber { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string status { get; set; }
        public string role { get; set; }
        // TODO: Add UUID guid
    }
}
